//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employeeid { get; set; }
        public string employeename { get; set; }
        public int departmentid { get; set; }
        public int designationid { get; set; }
        public string location { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual department department { get; set; }
        public virtual designation designation { get; set; }
    }
}
