//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storeDBEntities : DbContext
    {
        public storeDBEntities()
            : base("name=storeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<designation> designations { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<itemarrangement> itemarrangements { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<itemtype> itemtypes { get; set; }
        public virtual DbSet<manufacturer> manufacturers { get; set; }
        public virtual DbSet<racktype> racktypes { get; set; }
        public virtual DbSet<stockin> stockins { get; set; }
        public virtual DbSet<stockout> stockouts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
