//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoiceid { get; set; }
        public int customerid { get; set; }
        public int itemid { get; set; }
        public Nullable<System.DateTime> manufacturedate { get; set; }
        public Nullable<System.DateTime> expirydate { get; set; }
        public decimal unitprice { get; set; }
        public decimal discount { get; set; }
        public decimal quantity { get; set; }
        public string quantityunit { get; set; }
        public decimal totalprice { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual item item { get; set; }
    }
}
