//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemarrangement
    {
        public int arrangementid { get; set; }
        public int racktypeid { get; set; }
        public int categoryid { get; set; }
    
        public virtual itemtype itemtype { get; set; }
        public virtual racktype racktype { get; set; }
    }
}
