//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoice.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockin
    {
        public int stockinid { get; set; }
        public int itemid { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public string quantityunit { get; set; }
        public Nullable<System.DateTime> stockindate { get; set; }
    
        public virtual item item { get; set; }
    }
}
